"""Generate FEATURES.md from the registry (single source of truth: docs cannot drift)."""
from __future__ import annotations

from edgelab.features.spec import all_defs


def render_markdown() -> str:
    lines = ["# EdgeLab feature reference", "",
             "Generated by `python -m edgelab.cli features docs` from the feature registry.",
             "", "Conventions for every feature:", "",
             "- All outputs are float64 arrays aligned to the bars; NaN = not yet defined; events are 1.0/0.0.",
             "- **Known at**: `bar_close` means the value at bar t uses bars <= t only and may be used by a "
             "decision made at the close of bar t.",
             "- **Higher timeframe** (`timeframe: 15m` on 1m data): the value of the last COMPLETED "
             "higher-timeframe bar, exposed at min(bar open + timeframe, session close). Never a partial bar.",
             "- Every feature is verified by the truncation causality test (tests/test_feature_causality.py).",
             "- Identity: spec = {id, version, timeframe, params}; the cache key additionally includes the "
             "dataset hash, calendar, session definitions, implementation hash and dependency keys.", ""]
    lines.append("| id | v | category | requires | known at | causal | summary |")
    lines.append("|---|---|---|---|---|---|---|")
    for d in all_defs():
        lines.append(f"| `{d.feature_id}` | {d.version} | {d.category} | {', '.join(d.requires) or '-'} | "
                     f"{d.known_at} | {'yes' if d.causal else 'NO'} | {d.summary} |")
    for d in all_defs():
        desc = d.describe()
        lines += ["", f"## `{d.feature_id}` (version {d.version})", "", d.summary, "",
                  f"- **Input data:** OHLC{' + volume' if 'volume' in d.requires else ''} of the computed "
                  "timeframe; dataset calendar" + (" and session definitions" if d.session_params else ""),
                  "- **Timeframe:** native, or any multiple of it via `timeframe`",
                  f"- **Known at:** {d.known_at}   **Causal:** {'yes' if d.causal else 'NO'}",
                  f"- **Warm-up:** {d.warmup}",
                  f"- **Depends on:** {', '.join(desc['depends_on']) or '-'}",
                  f"- **Implementation hash:** `{desc['impl_hash']}`", "",
                  f"**Calculation.** {d.calculation}", "",
                  f"**Edge cases.** {d.edge_cases}", ""]
        if d.params:
            lines += ["| parameter | type | default | constraint | meaning |", "|---|---|---|---|---|"]
            for p in d.params:
                c = f"one of {list(p.choices)}" if p.choices else (f">= {p.min:g}" if p.min is not None else "")
                lines.append(f"| `{p.name}` | {p.kind.__name__} | `{p.default}` | {c} | {p.doc} |")
            lines.append("")
        lines += ["| output | meaning |", "|---|---|"]
        lines += [f"| `{n}` | {doc} |" for n, doc in d.outputs]
    return "\n".join(lines) + "\n"
